### ISSUE TITLE
Play 2.5 Upgrade (TODOs)

### ISSUE THREAD

**Issue by TBonnin** [guardian/frontend#13682]
Thanks to @alexduf for his extraordinary work 
# Cleanup
- [x] all lifecycle have useless default parameter
- [x] CorsHttpErrorHandler => remove alternate constructor
- [x] object IndexListingsLifecycle extends IndexListingsLifecycle
- [x] delete BackwardCompatibleLifecycleComponents
- [x] remove anotations @Singleton and @Inject com.google.inject
- [x] SingleServerSuite: remove dual mode support, and remove ugly globalSettingsOverride
- [x] search for import _root_ that are looking dodgy
- [x] delete StandaloneGlobal
- [x] delete Jobs object
- [x] delete AkkaAsync object
# TODO
- [x] Stop using WS
- [x] Stop using Akka.system()
- [x] Stop using Play.current
- [x] remaining deprecation warnings
# Play 2.5 Cleanup
- [x] FrontendApplicationLoader => remove fakeOnStart
- [x] remove route generator directive from frontend.scala
- [x] remove CSRFConfig workaround in FrontendComponents (Will only be release in Play 2.6)
- [x] AutoRefresh => change "pass by name" back to "pass by value" (Nice to have)
# Bonus
- [x] remove every single controller "object" => that involves touching the tests and isn't critically needed. It's nice to have
- [ ] Regroup all filters and httpHandlers under the package http
- [x] Stop using the Play default execution context (Instead use the context defined in the ExecutionContextComponent).
- [x] Healthcheck test port, it's weird
- [ ] delete the "Fake" object in identity and replace it with a proper testsuite
# PRs list

https://github.com/guardian/frontend/pull/13022
https://github.com/guardian/frontend/pull/13051
https://github.com/guardian/frontend/pull/13080
https://github.com/guardian/frontend/pull/13091
https://github.com/guardian/frontend/pull/13103
https://github.com/guardian/frontend/pull/13115
https://github.com/guardian/frontend/pull/13120
https://github.com/guardian/frontend/pull/13158
https://github.com/guardian/frontend/pull/13166
https://github.com/guardian/frontend/pull/13191
https://github.com/guardian/frontend/pull/13281
https://github.com/guardian/frontend/pull/13301
https://github.com/guardian/frontend/pull/13326
https://github.com/guardian/frontend/pull/13389
https://github.com/guardian/frontend/pull/13390
https://github.com/guardian/frontend/pull/13418
https://github.com/guardian/frontend/pull/13437
https://github.com/guardian/frontend/pull/13442
https://github.com/guardian/frontend/pull/13444
https://github.com/guardian/frontend/pull/13447
https://github.com/guardian/frontend/pull/13450
https://github.com/guardian/frontend/pull/13454
https://github.com/guardian/frontend/pull/13463
https://github.com/guardian/frontend/pull/13467
https://github.com/guardian/frontend/pull/13468
https://github.com/guardian/frontend/pull/13469
https://github.com/guardian/frontend/pull/13470
https://github.com/guardian/frontend/pull/13487
https://github.com/guardian/frontend/pull/13506
https://github.com/guardian/frontend/pull/13507
https://github.com/guardian/frontend/pull/13540
https://github.com/guardian/frontend/pull/13581
https://github.com/guardian/frontend/pull/13585
https://github.com/guardian/frontend/pull/13592
https://github.com/guardian/frontend/pull/13593
https://github.com/guardian/frontend/pull/13608
https://github.com/guardian/frontend/pull/13693
https://github.com/guardian/frontend/pull/13738
https://github.com/guardian/frontend/pull/13748
https://github.com/guardian/frontend/pull/13750
https://github.com/guardian/frontend/pull/13756
https://github.com/guardian/frontend/pull/13760
https://github.com/guardian/frontend/pull/13762
https://github.com/guardian/frontend/pull/13763
https://github.com/guardian/frontend/pull/13831
https://github.com/guardian/frontend/pull/13833
https://github.com/guardian/frontend/pull/13868
https://github.com/guardian/frontend/pull/13872
https://github.com/guardian/frontend/pull/14260
https://github.com/guardian/frontend/pull/14269
https://github.com/guardian/frontend/pull/14292
https://github.com/guardian/frontend/pull/14300
https://github.com/guardian/frontend/pull/14340
https://github.com/guardian/frontend/pull/14712
https://github.com/guardian/frontend/pull/14726
https://github.com/guardian/frontend/pull/14736
https://github.com/guardian/frontend/pull/15133
https://github.com/guardian/frontend/pull/15139
https://github.com/guardian/frontend/pull/15143
https://github.com/guardian/frontend/pull/15160
https://github.com/guardian/frontend/pull/15168
https://github.com/guardian/frontend/pull/15181
https://github.com/guardian/frontend/pull/15182
https://github.com/guardian/frontend/pull/15186
https://github.com/guardian/frontend/pull/15246
https://github.com/guardian/frontend/pull/15249
https://github.com/guardian/frontend/pull/15311
https://github.com/guardian/frontend/pull/15318
https://github.com/guardian/frontend/pull/15331
https://github.com/guardian/frontend/pull/15337
https://github.com/guardian/frontend/pull/15356

**Comment by TBonnin** [comment]
Closing this. Play 2.5 is out in production 1e8165f
