### ISSUE TITLE
Add ipsos iris tagging for Aus

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/frontend#24980]
## TODO
- [ ] Catch up with Mariot on past review
- [ ] Read through the [technical review](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/docs/architecture/3rd%20party%20technical%20review/002-ipsos-mori.md)
- [ ] Run a review through the tech council
- [ ] Update the [mapping file](https://github.com/guardian/frontend/blob/main/common/app/model/IpsosTags.scala) on recommendations from Audience (G Doc to be supplied)
  [new tags for aus](https://docs.google.com/document/d/1Eh2_ruCoAppMQvqHZ5jZFJaQk2OdHBmD0ZxS7H_Q9q4/edit)
- [ ] [Enable for not-just-gb audience](https://github.com/guardian/frontend/blob/b7013d96142798e24a16f58b855ddea18c45f2af/static/src/javascripts/projects/commercial/modules/ipsos-mori.ts#L30)

## Review

https://docs.google.com/document/d/1tWTD1tlc_Gv_qgAbEL7FkE_pAAfWcT66d8TmZ7oHrkg/edit

## Previous work

With the AU market moving from Nielsen to Ipsos for digital ratings in the next few months, we need to make sure that the AU site and sections are fully tagged and ready.

The Aus team want to ensure that the same tags dropped on the UK site are also dropped in Aus. In addition, the Aus team have some specific categories that need to be added in.

Jon Soul carried out a review of adding ipsos tagging onto the UK site: https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/docs/architecture/3rd%20party%20technical%20review/002-ipsos-mori.md.

We would likely need to perform a similar review before adding tagging for Australia.

In terms of technical implementation it looks like we've added uk tagging for amp and web.

For amp this is added in dcr: https://github.com/guardian/dotcom-rendering/pull/2396
For web this is added in the commercial bundle: https://github.com/guardian/frontend/blob/main/static/src/javascripts/projects/commercial/modules/ipsos-mori.ts

At the moment I'm not clear if the technical implementation needs to change, or in what ways.

---

forward to abi
