### ISSUE TITLE
Remove amp link from schema.org info

### ISSUE THREAD

**Issue by bryophyta** [guardian/frontend#25262]
Arising from [#25237](https://github.com/guardian/frontend/issues/25237).

Currently we are using an `amp` url as the `@id` for the schema.org data for liveblogs, articles, and interactives.

## Tasks
- [ ] Work out whether there is a good SEO reason for this.
- [ ] If not, replace it with the canonical `.com` url.
  - [ ] Possibly refactor the way that `DotcomRenderingDataModel.scala` gets the config it passes to the `LiveData` class: https://github.com/guardian/frontend/blob/48b447dd3414f7401fae6049c2d6db53534f39c9/common/app/model/dotcomrendering/DotcomRenderingDataModel.scala#L192-L196
