### ISSUE TITLE
Okta: increase Okta to 100%

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/frontend#26551]
## Steps

- Refactor the Okta switch from an Experiment (which has a participation group size of up to 50%) to a Feature Switch, which includes every user (100%)
- Refactor code which checks for Okta enrolment to just check whether the Okta switch is on

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/frontend/pull/26553
- [ ] https://github.com/guardian/dotcom-rendering/pull/8712
- [ ] https://github.com/guardian/commercial/pull/1039
``` 

In order to prevent a situation where some platforms know Okta as an experiment and others as a feature switch, the following release plan turns off the Okta switch entirely until all platforms treat it as a feature switch, at which point we can turn Okta back on.

```[tasklist]
### Release Plan
- [x] merge https://github.com/guardian/commercial/pull/1039
- [x] turn off the Okta switch in Frontend
- [x] merge https://github.com/guardian/frontend/pull/26553 & wait for deploy
- [x] merge https://github.com/guardian/dotcom-rendering/pull/8712 & wait for deploy
- [ ] https://github.com/guardian/frontend/pull/26562
- [x] turn the Okta switch back on
- [x] Send [comms](https://docs.google.com/document/d/1l4dJq7iJBlxYt0mz6EinXW7pvzX5aJg5o_MqR12SMQw/edit#heading=h.n3rfqmrq96fm)
```
