### ISSUE TITLE
Temporarily Increase Press Frequency Of Olympics Fronts

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/frontend#27330]
We may want to increase the press frequency of fronts where the olympics medal table snap[^1] will appear.

See #27270 for an example of how to do this.

```[tasklist]
### Tasks
- [ ] Find out on which fronts it will appear
- [ ] Increase the press frequencies
- [ ] Create a revert PR to decrease the press frequencies once the Olympics are over
```

[^1]: https://github.com/guardian/interactives/issues/1774
