### ISSUE TITLE
Temporarily Increase Press Frequency Of Paralympics Fronts

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/frontend#27390]
We may want to increase the press frequency of fronts where the Paralympics medal table snap[^1] will appear.

See #27330 for an example of how to do this.

```[tasklist]
### Tasks
- [x] Find out on which fronts it will appear
- [x] Increase the press frequencies
- [ ] Create a revert PR to decrease the press frequencies once the Paralympics are over
```

[^1]: https://github.com/guardian/interactives/issues/1827

**Comment by rowannekabalan** [comment]
Revert PR: https://github.com/guardian/frontend/pull/27468
