### ISSUE TITLE
Paralympics Subnav Changes

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/frontend#27409]
To be merged on the **27th of August**. Position is the same place as the Olympics 2024 entries from #27408 and #27418. Link is: https://www.theguardian.com/sport/paralympic-games-2024

```[tasklist]
### Tasks
- [ ] Add Paralympics 2024 to the main US subnav
- [ ] Add Paralympics 2024 to the US sport front subnav
- [ ] Add Paralympics 2024 to the UK sport front subnav
- [ ] Add Paralympics 2024 to the AU sport front subnav
```
